### PR TITLE
Misc for #1054

### LINKED ISSUE #1054: lpmi NullReferenceException
4/17/2023 7:10:05 PM: System.NullReferenceException: Object reference not set to an instance of an object.
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Ipmi.Update(StringBuilder stringBuilder) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Ipmi.cs:line 190

See https://github.com/Rem0o/FanControl.Releases/issues/1723

I believe @lukefor created that class. 

There ain't that many vars that can go wrong near line 190.
All I see is 
```c#
 _voltages.Add(RawToFloat(reading[1], sdr));

// _voltages is a read-only list
// reading is an array of byte, which would explode earlier if it was null
// sdr is a struct, which can't be null. 
```

### PR DESCRIPTION
**Pull request by PhyxionNL**

### CODE REVIEW

File: LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Ipmi.cs [hunk 1]
```diff
@@ -133,33 +131,34 @@ private unsafe void Update(StringBuilder stringBuilder)
...
                     {
                         recordLower = sdrRaw[1];
                         recordUpper = sdrRaw[2];
 
-                        Interop.Ipmi.Sdr sdr;
-
                         fixed (byte* pSdr = sdrRaw)
                         {
-                            sdr = (Interop.Ipmi.Sdr)Marshal.PtrToStructure((IntPtr)pSdr + 3, typeof(Interop.Ipmi.Sdr));
+                            object sdrObj = Marshal.PtrToStructure((IntPtr)pSdr + 3, typeof(Interop.Ipmi.Sdr));
```
Comment (doolbneerg) [inline LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Ipmi.cs:153]: I am not sure you why would check the return of the Marshal. That should either be a valid pointer, or it should throw an exception.
