### PR TITLE
Fix null reference in MemoryGroup when Ring0 is disabled.

### LINKED ISSUE #1795: Opting out of Ring0 causes SMBusManager.DetectSMBuses to fail
I was trying out the ability to opt out of Ring0 introduced by #1765. When `_ring0Enabled = false` I get a `NullReferenceException` in [MemoryGroup.cs, line 95](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Memory/MemoryGroup.cs#L95). This is because RAMSPDToolkit's `DriverManager` isn't initialized properly when Ring0 isn't open.

### PR DESCRIPTION
**Pull request by xnaught**
Fixes #1795.

### CODE REVIEW

File: LibreHardwareMonitorLib/Hardware/Memory/MemoryGroup.cs [hunk 1]
```diff
@@ -37,6 +37,13 @@ static MemoryGroup()
             DriverManager.Driver = new RAMSPDToolkitDriver(Ring0.KernelDriver);
             SMBusManager.UseWMI = false;
         }
+        else
+        {
+            // Still need to set Driver if Ring0 is absent. RAMSPDToolkitDriver.IsOpen
+            // returns false when the given kernel driver is null.
+            DriverManager.Driver = new RAMSPDToolkitDriver(null);
+            SMBusManager.UseWMI = true;
```
Comment (xnaught) [inline LibreHardwareMonitorLib/Hardware/Memory/MemoryGroup.cs]: Is it correct to fallback to WMI here?  (`UseWMI = true`)

Comment (PhyxionNL) [reply LibreHardwareMonitorLib/Hardware/Memory/MemoryGroup.cs]: No, SMBusManager doesn't use Ring0.
