### PR TITLE
Fix memory only being available for Intel

### LINKED ISSUE #1874: The latest master build doesn't show memory temperatures
The latest master build doesn't show memory temperatures. Wondering if this is a PawnIO issue? The kits are from G.Skill.

Image

### PR DESCRIPTION
**Pull request by Blacktempel**
Fixes #1874

### CODE REVIEW

**Comment by jerrylzy** [comment]
This won't fix #1874 but is needed. Changes are needed on the RAMSPDToolkit or PawnIO side.

File: LibreHardwareMonitorLib/PawnIo/PawnIo.cs [hunk 1]
```diff
@@ -41,6 +41,8 @@ public static bool IsInstalled
         get { return !string.IsNullOrEmpty(InstallPath); }
     }
 
+    public bool IsValid => _handle != IntPtr.Zero;
```
Comment (jerrylzy) [inline LibreHardwareMonitorLib/PawnIo/PawnIo.cs]: IsPawnIOLoaded? The rest LGTM.

**Comment by jerrylzy** [comment]
Looks like .NET 8's version is already working. I'm pretty sure `Convert.ToUInt64` in the `RAMSPDToolkit.Utilities.BitHandler.GetBits` function is the only thing failing on .NET Framework.
image

**Comment by Blacktempel** [comment]
Yes it was only for .NET Framework.
.NET 8 is using a different logic.

File: LibreHardwareMonitorLib/PawnIo/PawnIo.cs (hunk 1 above)
Comment (Blacktempel) [reply LibreHardwareMonitorLib/PawnIo/PawnIo.cs]: Changed it to `IsLoaded`.

**Review by jerrylzy — APPROVED** [review]
