### PR TITLE
 Fix buffer over-read causing AccessViolationException in NVMeSamsung

### LINKED ISSUE #141: AccessViolationException in NVMeSamsung
Since the big refactoring pr I started getting exceptions when initializing samsung nvme ssd.
I have to let it crash a couple of times and then it works fine.

Also normal ssd sensor data takes very long to update, but again only a couple of times. Then it updates fast.

I guess there is a problem with capturing smart data? I have no idea how to debug/fix this.
Probably broken since [this](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/db51d7f509caba7db9d0721d56d80c9f7972f187) commit.

NVME: Samsung 950 PRO
SSD: Samsung 850 EVO
Win: 10.0.18362.388
LibreHardwareMonitor: Build from [61454e1ae2f2ce18550bbb337719e39a3058884f](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/61454e1ae2f2ce18550bbb337719e39a3058884f)

Exception 1:
```
System.AccessViolationException
   in System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   in System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr, System.Type)
   in System.Runtime.InteropServices.Marshal.PtrToStructure[[LibreHardwareMonitor.Interop.Kernel32+NVME_IDENTIFY_CONTROLLER_DATA, LibreHardwareMonitorLib, Version=0.8.1.0, Culture=neutral, PublicKeyToken=null]](IntPtr)
   in LibreHardwareMonitor.Hardware.Storage.NVMeSamsung.IdentifyController(System.Runtime.InteropServices.SafeHandle, NVME_IDENTIFY_CONTROLLER_DATA ByRef)
   in LibreHardwareMonitor.Hardware.Storage.NVMeSmart.GetInfo()
   in LibreHardwareMonitor.Hardware.Storage.NVMeGeneric.GetDeviceInfo(LibreHardwareMonitor.Hardware.Storage.StorageInfo)
   in LibreHardwareMonitor.Hardware.Storage.NVMeGeneric.CreateInstance(LibreHardwareMonitor.Hardware.Storage.StorageInfo, LibreHardwareMonitor.Hardware.ISettings)
   in LibreHardwareMonitor.Hardware.Storage.AbstractStorage.CreateInstance(System.String, UInt32, UInt64, Int32, LibreHardwareMonitor.Hardware.ISettings)
   in LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
   in LibreHardwareMonitor.Hardware.Computer.Open()
```

Exception 2:
```
System.ExecutionEngineException
   in System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   in System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr, System.Type)
   in System.Runtime.InteropServices.Marshal.PtrToStructure[[LibreHardwareMonitor.Interop.Kernel32+NVME_IDENTIFY_CONTROLLER_DATA, LibreHardwareMonitorLib, Version=0.8.1.0, Culture=neutral, PublicKeyToken=null]](IntPtr)
   in LibreHardwareMonitor.Hardware.Storage.NVMeSamsung.IdentifyController(System.Runtime.InteropServices.SafeHandle, NVME_IDENTIFY_CONTROLLER_DATA ByRef)
   in LibreHardwareMonitor.Hardware.Storage.NVMeSmart.GetInfo()
   in LibreHardwareMonitor.Hardware.Storage.NVMeGeneric.GetDeviceInfo(LibreHardwareMonitor.Hardware.Storage.StorageInfo)
   in LibreHardwareMonitor.Hardware.Storage.NVMeGeneric.CreateInstance(LibreHardwareMonitor.Hardware.Storage.StorageInfo, LibreHardwareMonitor.Hardware.ISettings)
   in LibreHardwareMonitor.Hardware.Storage.AbstractStorage.CreateInstance(System.String, UInt32, UInt64, Int32, LibreHardwareMonitor.Hardware.ISettings)
   in LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
   in LibreHardwareMonitor.Hardware.Computer.Open()

### PR DESCRIPTION
**Pull request by MoshiMoshi0**
The data buffer size in `SCSI_PASS_THROUGH_WITH_BUFFERS` is set to only 512 bytes but it is used to create `NVME_IDENTIFY_CONTROLLER_DATA` which is 4096 bytes with `Marshal.PtrToStructure`. This causes buffer over-read.

This could also be solved by creating a new memory block that fits `NVME_IDENTIFY_CONTROLLER_DATA` and copying the smaller `SCSI_PASS_THROUGH_WITH_BUFFERS.DataBuf` there. This is done in [NVMeIntel.cs](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/bae89127b2d6c1813a9b8736a63a5c997541ff9a/LibreHardwareMonitorLib/Hardware/Storage/NVMeIntel.cs#L53-L60)

I think this should wait for sebastian-dev to approve this as he is the author of the nvme support.

Fixes #141

### CODE REVIEW

File: LibreHardwareMonitorLib/Interop/Kernel32.cs [hunk 1]
```diff
@@ -728,7 +727,7 @@ internal struct SCSI_PASS_THROUGH_WITH_BUFFERS
             [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
             public byte[] SenseBuf;
 
-            [MarshalAs(UnmanagedType.ByValArray, SizeConst = SCSI_PASS_THROUGH_BUFFER_SIZE)]
+            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4096)]
```
Comment (Phyxion) [inline LibreHardwareMonitorLib/Interop/Kernel32.cs]: If this is always the size of NVME_IDENTIFY_CONTROLLER_DATA, perhaps it would be useful to create a const NVME_IDENTIFY_CONTROLLER_DATA_SIZE so it's obvious why this is this size.

Comment (MoshiMoshi0) [reply LibreHardwareMonitorLib/Interop/Kernel32.cs]: From what i've read you can set the size of the buffer of `SCSI_PASS_THROUGH_WITH_BUFFERS` to what ever you need. I've just set it to the size of `NVME_IDENTIFY_CONTROLLER_DATA` to fix this bug, but it can be bigger if needed in the future. Also a const would have to be updated if some day `NVME_IDENTIFY_CONTROLLER_DATA` struct is changed, so I think just using `Marshal.SizeOf` is safer.

And the reason I removed `SCSI_PASS_THROUGH_BUFFER_SIZE` const is to match the code in NVMeIntel/NVMeIntelRst ([1](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/61454e1ae2f2ce18550bbb337719e39a3058884f/LibreHardwareMonitorLib/Interop/Kernel32.cs#L695), [2](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/61454e1ae2f2ce18550bbb337719e39a3058884f/LibreHardwareMonitorLib/Hardware/Storage/NVMeIntel.cs#L42)) and NVMeWindows ([1](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/61454e1ae2f2ce18550bbb337719e39a3058884f/LibreHardwareMonitorLib/Interop/Kernel32.cs#L1248), [2](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/61454e1ae2f2ce18550bbb337719e39a3058884f/LibreHardwareMonitorLib/Hardware/Storage/NVMeWindows.cs#L32)). They also have a bigger than needed buffer size of 4096, no constants, and use `(uint)o.DataBuffer.Length` where the size of the buffer is needed.

Comment (Phyxion) [reply LibreHardwareMonitorLib/Interop/Kernel32.cs]: OK, sounds good. Did you test this already? It looks good to me but I don't have a Samsung NVMe to test.

Comment (MoshiMoshi0) [reply LibreHardwareMonitorLib/Interop/Kernel32.cs]: The ssds are detected, the sensor values are valid and I have not crashed since this change.

I tested by running a program that just initializes and lists sensors since I could not reproduce this 100% of the time. And it would crash every couple of runs before the change.

Comment (Phyxion) [reply LibreHardwareMonitorLib/Interop/Kernel32.cs]: Still working OK? It looks good to merge but I cannot test this myself.

Comment (MoshiMoshi0) [reply LibreHardwareMonitorLib/Interop/Kernel32.cs]: Yes, I guess it would be good for someone else to also test this but I haven't had any exceptions after this change.
