### PR TITLE
Fixed temperatures for NCT6796D... and added ASUS TUF GAMING B550M-PLUS (WI-FI)

### LINKED ISSUE #335: More sensors for Nuvoton NCT6798D
The Nuvoton NCT6798D on my Asus TUF Gaming B550M-Plus (Wi-Fi) appears to be supporting more temperature sensors than are currently read out in LHM.
They are visible both in BIOS and in HWiNFO and show reasonable values, so they seem to be really there and not just unconnected ports. Which is a bit of a shame, because the "CPU temperature" used by the BIOS to control the fans is one of the sensors missing.

I had a look at how support for the NCT6798D was added in PR #79 and it looks like it was just enabled as a supported sensor in the generic NCT677X support. Maybe we need a new support for NCT679X chips with at least 3 more temperature sensors.
Also I'm a bit surprised to see 7 temperature sensors configured in NCT677X.cs, but only 6 are visible (none hidden) when I run the program. Is there some other part in the code that removes sensors again if the values are bogus or something like that?

I'm willing to dig into that, but I'm missing some fundamental build instructions. I gathered I need Visual Studio. VSCode is not enough?

### PR DESCRIPTION
**Pull request by holgerpieta**
Updated temperature readings for NCT6796D, NCT6796DR, NCT6797D and NCT6798D based on the available documentation for NCT6796D.
No documentation could be found for the later models, so I assumed they are similar.

Also added ASUS TUF GAMING B550M-PLUS (WI-FI) to the list of supported mainboards.

I'm not yet happy with the names for the temperatures, e.g. PECI appears to be an Intel thing and not AMD. But to fix the names more info is needed, about which temperature source is measuring what.
The badly named PECI seems to be the temperature used by the board to control fans.
Other temperatures behave rather weirdly, i.e. AUX0 starts well above 80 °C and goes down when the system heats up.

Fixes #335

### CODE REVIEW

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs [hunk 1]
```diff
@@ -2128,6 +2128,56 @@ private static void GetNuvotonConfigurationD(ISuperIO superIO, Manufacturer manu
...
+                            t.Add(new Temperature("PECI 0", 9));
+                            t.Add(new Temperature("PECI 1", 10));
+                            t.Add(new Temperature("PCH Chip CPU Max", 11));
+                            t.Add(new Temperature("PCH Chip", 12));
+                            t.Add(new Temperature("PCH CPU", 13));
+                            t.Add(new Temperature("PCH MCH", 14));
+                            t.Add(new Temperature("Agent 0 Dimm 0", 15));
+                            t.Add(new Temperature("Agent 0 Dimm 1", 16));
+                            t.Add(new Temperature("Agent 1 Dimm 0", 17));
+                            t.Add(new Temperature("Agent 1 Dimm 1", 18));
```
Comment (PhyxionNL) [inline LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2166]: Can you format this similar to the rest? I.e. DIMM.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs [hunk 2]
```diff
@@ -2128,6 +2128,56 @@ private static void GetNuvotonConfigurationD(ISuperIO superIO, Manufacturer manu
...
+                            t.Add(new Temperature("Byte 0", 19));
+                            t.Add(new Temperature("Byte 1", 20));
```
Comment (PhyxionNL) [inline LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2168]: Is this even useful to add?

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs [hunk 3]
```diff
@@ -2128,6 +2128,56 @@ private static void GetNuvotonConfigurationD(ISuperIO superIO, Manufacturer manu
...
+                            t.Add(new Temperature("PECI 0 Cal", 21));
+                            t.Add(new Temperature("PECI 1 Cal", 22));
```
Comment (PhyxionNL) [inline LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2170]: Cal of Calibrate? Or something else? Might be worth writing this out.

**Review by PhyxionNL — CHANGES_REQUESTED** [review]
Finally a sensor I can try on my own system. 

Some small changes requested, but there are also some other issues. At least with NCT6797D.
I no longer have a VRM MOS sensor (which does exist and works in current build). Also "System" temperature is now swapped with CPU and no longer correct.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 1 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2166]: Of course, will do. Though I'm hardly sure that actually got anything to do with DIMM as in RAM. But it may be. The NCT docs aren't exactly helpful about that.

Comment (PhyxionNL) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2166]: Should be DIMM/RAM: https://patchwork.kernel.org/project/linux-hwmon/patch/1537451141-27242-11-git-send-email-linux@roeck-us.net/

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 2 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2168]: It's in the list of possible temperature source, but the docs again do not indicate what it purpose might be. We may rename it to Device0 and Device1, which would also match the docs but still doesn't tell us anything useful.

Comment (PhyxionNL) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2168]: OK, let's keep it then 👍

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 3 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2170]: That's something which is actually a bit better explained in the docs but still somewhat far from logical.
PECI is the Intel interface used to report CPU temperatures to the mainboard. It should not work on AMD boards and does not on my system (values PECI 0 and PECI 1). So far so good.
But the docs now explain that PECI values are notoriously imprecise, so there is an option to "automatically calibrate" them based on temperature probes (though no explanation what probe is used). For some unknown reasons this value ("PECI 0 Calibration") is the value used by my ASUS board to control the fan speeds. It's showing a value that's correlated to CPU temperature, though usually about 10 K lower. That's actually the value I did all the work for, because I wanted to see the temperature that controls fan speed.
Officially it's called "PECI Agent 0 Calibration".

Comment (PhyxionNL) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2170]: Then I think these sensor names should end with Calibration, it makes more sense than just Cal here and there's room for it in the UI 🙂

**Comment by holgerpieta** [comment]
Generally regarding names: I wanted to keep them brief to not blow up the gadget, but maybe it's better to have them long and if the user wants them shorter she can rename the signals.

Back to your board: Would you mind telling you what board you're using? I had planned to have the changes not affect anything but my ASUS board, but they turned out to be much more complex than I thought, so probably something went wrong.
I'll check that again and come up with some fixes.

**Comment by PhyxionNL** [comment]
> 
> 
> Generally regarding names: I wanted to keep them brief to not blow up the gadget, but maybe it's better to have them long and if the user wants them shorter she can rename the signals.
> 
> Back to your board: Would you mind telling you what board you're using? I had planned to have the changes not affect anything but my ASUS board, but they turned out to be much more complex than I thought, so probably something went wrong.
> I'll check that again and come up with some fixes.

MSI B450-A Pro, it uses the NCT6797D sensor.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 1 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2166]: Will do, but the docs aren't exactly helpful to see if DIMM actually got something to do with RAM or if it is supposed to mean something else. On my board they're empty anyway.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 2 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2168]: Again the docs aren't helpful at all here. They are in the list of possible temperature sources. They could also be called Device 0 and Device 1, but no infos about what devices that may be. And again they're not used on my board.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 3 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2170]: There is actually something about that in the docs, but it doesn't make a lot of sense, either.
PECI is the Intel interface to report CPU temperatures to the board. They should not work on AMD and they (PECI 0 and PECI 1) are indeed no used on my board.
But now the docs claim that PECI values are notoriously bad, so they can be "calibrated" (what ever that means) by using temperature probes. There is some explanation about how calibration work (it's automagic), but not even which temperature probes are used.
Oddly enough, "PECI 0 Calibration" shows values on my system (which is AMD) and those values are actually used to control fan speeds. The value is roughly correlated to CPU temperature (read out directly), but usually about 10 to 15 K lower.
It's actually the value I did all the work for.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 1 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2166]: Perfect, I'll rename them.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 2 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2168]: I think Device 0 and Device 1 is better, so I'll rename them, too.

File: LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (hunk 3 above)
Comment (holgerpieta) [reply LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs:2170]: Yes, will do.

**Comment by holgerpieta** [comment]
Sensors renamed and reordered to match what it had been before. That should solve your problem of swapped sensors.
Also added the missing fractional bit for temperature register 0x150.

There are some major differences left that may cause regressions, though if that worked before it was pure luck, I think.
First of all temperature registers are now scanned from left to right and if a source has been found before, it will not be overwritten.
Previously, they were scanned from right to left and any source encountered again was just overwritten. I thought that this should not make a difference, because values should be same if the same source is encountered again, but maybe that's not correct.
It might still be wise to go back to right-to-left to avoid odd problems somewhere else.

Also, if I compare lines 177-183 of LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Nct677X.cs to line 2275-2279 of LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs (all files before my changes), it looks to me that CPU and PECI have been confused before. But maybe I'm the one getting confused here.

**Comment by PhyxionNL** [comment]
The sensors now all exist again on my machine and report the same values as before. I checked against HWiNFO and there are some differences in temperatures. 

HWiNFO:
image

LHM:
image

The PECI is ~7 degrees off. I reverted back the original order you had for `_temperaturesSource`, and then I have 5 temperature sensors instead of 4 (System and VRM MOS are mostly the same, 0-0.5 degrees difference):

image

I installed MSI's Dragon software to check what they read out (PECI doesn't exist there):
image

So at least the original order doesn't seem correct. I don't know who is correct for the PECI temperature, but HWMonitor is also reporting 40 degrees for it.

**Comment by holgerpieta** [comment]
The list of temperature sensors for B450A-Pro in lines 2267-2271 of LibreHardwareMonitorLib\Hardware\Motherboard\SuperIOHardware.cs (version of this PR) is awfully short, so I wouldn't be surprised if we're just missing sensors. Maybe just copy over the full list from my ASUS board (lines 2148-2171) and check what more sensors you can find. Maybe one of them (I'd suggest PECI 0 Calibrated) shows the same CPU temp as the Dragon SW.

**Comment by PhyxionNL** [comment]
This board doesn't have a lot of sensors, if you copy in the content from the ASUS board:

image

System & AUX are OK with other sensors, but the CPU/PECI one remains off. It doesn't seem to change much after LHM launch, but it's always been 33 and 37 degrees. Any ideas?

**Comment by holgerpieta** [comment]
Something wicked is going on I do not understand in the moment.
Please try the following:
- My code.
- But copy over the temperature configuration from my board to your board.
- In the folder where the exe is, find a file called LibreHardwareMonitor.exe.config and edit its content:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <system.diagnostics>
    <trace autoflush="false" indentsize="4">
      <listeners>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="TextWriterOutput.log" />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
</configuration>
```
- Start LHM and let it run for a couple of seconds.
- Attach the file TextWriterOutput.log here.

There is no debug output in the old version, but my new version has some debug output, then we can see what sensor values is found in which register.

**Comment by PhyxionNL** [comment]
Here, a couple of updates:

Updating temperatures.
Temperature register 0 value (integer): 64/0.5
Temperature register 0 value updated (fractional): 64/0.5
Temperature register 0 source: 1
Temperature register 0 final temperature: 32.
Temperature register 0 accepted.
Temperature register 1 value (integer): 64/0.5
Temperature register 1 value updated (fractional): 64/0.5
Temperature register 1 source: 1
Temperature 1 discarded, because source seen before.
Temperature register 2 value (integer): 64/0.5
Temperature register 2 value updated (fractional): 64/0.5
Temperature register 2 source: 1
Temperature 2 discarded, because source seen before.
Temperature register 3 value (integer): 64/0.5
Temperature register 3 value updated (fractional): 64/0.5
Temperature register 3 source: 1
Temperature 3 discarded, because source seen before.
Temperature register 4 value (integer): 64/0.5
Temperature register 4 value updated (fractional): 64/0.5
Temperature register 4 source: 1
Temperature 4 discarded, because source seen before.
Temperature register 5 value (integer): 108/0.5
Temperature register 5 value updated (fractional): 109/0.5
Temperature register 5 source: 8
Temperature register 5 final temperature: 54.5.
Temperature register 5 accepted.
Temperature register 6 value (integer): 84/0.5
Temperature register 6 value updated (fractional): 85/0.5
Temperature register 6 source: 3
Temperature register 6 final temperature: 42.5.
Temperature register 6 accepted.
Temperature register 7 value (integer): 64/0.5
Temperature register 7 source: 1
Temperature 7 discarded, because source seen before.
Temperature register 8 value (integer): 84/0.5
Temperature register 8 value updated (fractional): 85/0.5
Temperature register 8 source: 3
Temperature 8 discarded, because source seen before.
Temperature register 9 value (integer): -2/0.5
Temperature register 9 source: 31
Temperature register 9 final temperature: -1.
Temperature register 9 accepted.
Temperature register 10 value (integer): -2/0.5
Temperature register 10 source: 31
Temperature register 10 final temperature: -1.
Temperature register 10 accepted.
Temperature register 11 value (integer): -2/0.5
Temperature register 11 source: 31
Temperature register 11 final temperature: -1.
Temperature register 11 accepted.
Temperature register 12 value (integer): -2/0.5
Temperature register 12 source: 31
Temperature register 12 final temperature: -1.
Temperature register 12 accepted.
Temperature register 13 value (integer): -2/0.5
Temperature register 13 source: 31
Temperature register 13 final temperature: -1.
Temperature register 13 accepted.
Temperature register 14 value (integer): -2/0.5
Temperature register 14 source: 31
Temperature register 14 final temperature: -1.
Temperature register 14 accepted.
Alternate temperature register 0 skipped, because value already filled.
Alternate temperature register 1 final temperature: 38.
Alternate temperature register 2 skipped, because bit already set.
Alternate temperature register 3 skipped, because bit already set.
Alternate temperature register 4 final temperature: -128.
Alternate Temperature register 4 discarded: Out of range.
Alternate temperature register 5 final temperature: 43.
Alternate temperature register 6 final temperature: -2.
Alternate Temperature register 6 discarded: Out of range.
Alternate temperature register 7 skipped, because value already filled.
Alternate temperature register 8 skipped, because value already filled.
Alternate temperature register 9 skipped, because value already filled.
Alternate temperature register 10 skipped, because value already filled.
Alternate temperature register 11 final temperature: 0.
Alternate Temperature register 11 discarded: Out of range.
Alternate temperature register 12 final temperature: 0.
Alternate Temperature register 12 discarded: Out of range.
Alternate temperature register 13 final temperature: 0.
Alternate Temperature register 13 discarded: Out of range.
Alternate temperature register 14 final temperature: 0.
Alternate Temperature register 14 discarded: Out of range.
Alternate temperature register 15 skipped, because value already filled.
Alternate temperature register 16 skipped, because value already filled.
Alternate temperature register 17 skipped, because value already filled.
Alternate temperature register 18 skipped, because value already filled.
Alternate temperature register 19 skipped, because value already filled.
Alternate temperature register 20 skipped, because value already filled.
Alternate temperature register 21 skipped, because value already filled.
Alternate temperature register 22 skipped, because value already filled.
Alternate temperature register 23 skipped, because value already filled.
Updating temperatures.
Temperature register 0 value (integer): 64/0.5
Temperature register 0 value updated (fractional): 65/0.5
Temperature register 0 source: 1
Temperature register 0 final temperature: 32.5.
Temperature register 0 accepted.
Temperature register 1 value (integer): 64/0.5
Temperature register 1 value updated (fractional): 65/0.5
Temperature register 1 source: 1
Temperature 1 discarded, because source seen before.
Temperature register 2 value (integer): 64/0.5
Temperature register 2 value updated (fractional): 65/0.5
Temperature register 2 source: 1
Temperature 2 discarded, because source seen before.
Temperature register 3 value (integer): 64/0.5
Temperature register 3 value updated (fractional): 65/0.5
Temperature register 3 source: 1
Temperature 3 discarded, because source seen before.
Temperature register 4 value (integer): 64/0.5
Temperature register 4 value updated (fractional): 65/0.5
Temperature register 4 source: 1
Temperature 4 discarded, because source seen before.
Temperature register 5 value (integer): 108/0.5
Temperature register 5 value updated (fractional): 109/0.5
Temperature register 5 source: 8
Temperature register 5 final temperature: 54.5.
Temperature register 5 accepted.
Temperature register 6 value (integer): 82/0.5
Temperature register 6 value updated (fractional): 83/0.5
Temperature register 6 source: 3
Temperature register 6 final temperature: 41.5.
Temperature register 6 accepted.
Temperature register 7 value (integer): 64/0.5
Temperature register 7 source: 1
Temperature 7 discarded, because source seen before.
Temperature register 8 value (integer): 82/0.5
Temperature register 8 value updated (fractional): 83/0.5
Temperature register 8 source: 3
Temperature 8 discarded, because source seen before.
Temperature register 9 value (integer): -2/0.5
Temperature register 9 source: 31
Temperature register 9 final temperature: -1.
Temperature register 9 accepted.
Temperature register 10 value (integer): -2/0.5
Temperature register 10 source: 31
Temperature register 10 final temperature: -1.
Temperature register 10 accepted.
Temperature register 11 value (integer): -2/0.5
Temperature register 11 source: 31
Temperature register 11 final temperature: -1.
Temperature register 11 accepted.
Temperature register 12 value (integer): -2/0.5
Temperature register 12 source: 31
Temperature register 12 final temperature: -1.
Temperature register 12 accepted.
Temperature register 13 value (integer): -2/0.5
Temperature register 13 source: 31
Temperature register 13 final temperature: -1.
Temperature register 13 accepted.
Temperature register 14 value (integer): -2/0.5
Temperature register 14 source: 31
Temperature register 14 final temperature: -1.
Temperature register 14 accepted.
Alternate temperature register 0 skipped, because value already filled.
Alternate temperature register 1 final temperature: 37.
Alternate temperature register 2 skipped, because bit already set.
Alternate temperature register 3 skipped, because bit already set.
Alternate temperature register 4 final temperature: -128.
Alternate Temperature register 4 discarded: Out of range.
Alternate temperature register 5 final temperature: 43.
Alternate temperature register 6 final temperature: -3.
Alternate Temperature register 6 discarded: Out of range.
Alternate temperature register 7 skipped, because value already filled.
Alternate temperature register 8 skipped, because value already filled.
Alternate temperature register 9 skipped, because value already filled.
Alternate temperature register 10 skipped, because value already filled.
Alternate temperature register 11 final temperature: 0.
Alternate Temperature register 11 discarded: Out of range.
Alternate temperature register 12 final temperature: 0.
Alternate Temperature register 12 discarded: Out of range.
Alternate temperature register 13 final temperature: 0.
Alternate Temperature register 13 discarded: Out of range.
Alternate temperature register 14 final temperature: 0.
Alternate Temperature register 14 discarded: Out of range.
Alternate temperature register 15 skipped, because value already filled.
Alternate temperature register 16 skipped, because value already filled.
Alternate temperature register 17 skipped, because value already filled.
Alternate temperature register 18 skipped, because value already filled.
Alternate temperature register 19 skipped, because value already filled.
Alternate temperature register 20 skipped, because value already filled.
Alternate temperature register 21 skipped, because value already filled.
Alternate temperature register 22 skipped, because value already filled.
Alternate temperature register 23 skipped, because value already filled.
Updating temperatures.
Temperature register 0 value (integer): 64/0.5
Temperature register 0 value updated (fractional): 65/0.5
Temperature register 0 source: 1
Temperature register 0 final temperature: 32.5.
Temperature register 0 accepted.
Temperature register 1 value (integer): 64/0.5
Temperature register 1 value updated (fractional): 65/0.5
Temperature register 1 source: 1
Temperature 1 discarded, because source seen before.
Temperature register 2 value (integer): 64/0.5
Temperature register 2 value updated (fractional): 65/0.5
Temperature register 2 source: 1
Temperature 2 discarded, because source seen before.
Temperature register 3 value (integer): 64/0.5
Temperature register 3 value updated (fractional): 65/0.5
Temperature register 3 source: 1
Temperature 3 discarded, because source seen before.
Temperature register 4 value (integer): 64/0.5
Temperature register 4 value updated (fractional): 65/0.5
Temperature register 4 source: 1
Temperature 4 discarded, because source seen before.
Temperature register 5 value (integer): 108/0.5
Temperature register 5 value updated (fractional): 108/0.5
Temperature register 5 source: 8
Temperature register 5 final temperature: 54.
Temperature register 5 accepted.
Temperature register 6 value (integer): 82/0.5
Temperature register 6 value updated (fractional): 83/0.5
Temperature register 6 source: 3
Temperature register 6 final temperature: 41.5.
Temperature register 6 accepted.
Temperature register 7 value (integer): 64/0.5
Temperature register 7 source: 1
Temperature 7 discarded, because source seen before.
Temperature register 8 value (integer): 82/0.5
Temperature register 8 value updated (fractional): 83/0.5
Temperature register 8 source: 3
Temperature 8 discarded, because source seen before.
Temperature register 9 value (integer): -2/0.5
Temperature register 9 source: 31
Temperature register 9 final temperature: -1.
Temperature register 9 accepted.
Temperature register 10 value (integer): -2/0.5
Temperature register 10 source: 31
Temperature register 10 final temperature: -1.
Temperature register 10 accepted.
Temperature register 11 value (integer): -2/0.5
Temperature register 11 source: 31
Temperature register 11 final temperature: -1.
Temperature register 11 accepted.
Temperature register 12 value (integer): -2/0.5
Temperature register 12 source: 31
Temperature register 12 final temperature: -1.
Temperature register 12 accepted.
Temperature register 13 value (integer): -2/0.5
Temperature register 13 source: 31
Temperature register 13 final temperature: -1.
Temperature register 13 accepted.
Temperature register 14 value (integer): -2/0.5
Temperature register 14 source: 31
Temperature register 14 final temperature: -1.
Temperature register 14 accepted.
Alternate temperature register 0 skipped, because value already filled.
Alternate temperature register 1 final temperature: 37.
Alternate temperature register 2 skipped, because bit already set.
Alternate temperature register 3 skipped, because bit already set.
Alternate temperature register 4 final temperature: -128.
Alternate Temperature register 4 discarded: Out of range.
Alternate temperature register 5 final temperature: 43.
Alternate temperature register 6 final temperature: -3.
Alternate Temperature register 6 discarded: Out of range.
Alternate temperature register 7 skipped, because value already filled.
Alternate temperature register 8 skipped, because value already filled.
Alternate temperature register 9 skipped, because value already filled.
Alternate temperature register 10 skipped, because value already filled.
Alternate temperature register 11 final temperature: 0.
Alternate Temperature register 11 discarded: Out of range.
Alternate temperature register 12 final temperature: 0.
Alternate Temperature register 12 discarded: Out of range.
Alternate temperature register 13 final temperature: 0.
Alternate Temperature register 13 discarded: Out of range.
Alternate temperature register 14 final temperature: 0.
Alternate Temperature register 14 discarded: Out of range.
Alternate temperature register 15 skipped, because value already filled.
Alternate temperature register 16 skipped, because value already filled.
Alternate temperature register 17 skipped, because value already filled.
Alternate temperature register 18 skipped, because value already filled.
Alternate temperature register 19 skipped, because value already filled.
Alternate temperature register 20 skipped, because value already filled.
Alternate temperature register 21 skipped, because value already filled.
Alternate temperature register 22 skipped, because value already filled.
Alternate temperature register 23 skipped, because value already filled.

**Comment by holgerpieta** [comment]
Ok, just noticed the debug output wasn't optimal, but that's fixed now.
And it won't stop us from working, so, let's see.

The first 5 registers read from the same source (1, i.e. SYS), so it's only stored once, but that doesn't matter, because they all got the same value (32 °C) anyway.
Then we see source 8 (SMBUS0) at 54.5 °C.
Followed by source 3 (AUX0) at 42.5 °C.
Then we see source 1 and 3 again, again with the same values, so that's fine.
All following registers use source 31 (VIRTUAL) and read -1 °C, so I guess they are not used.
However, here we have a bug causing the program to forgot that it already read that source and so writes it again a couple of times. But it's -1 each time, so that's not actually a problem. Fixed it anyway.
So, ignoring the bogus VIRTUAL, at that point we've read 3 temperatures.

In the second step, checking the alternative registers, we find:
CPU: 38 °C
AUX2: 48 °C
AUX1: -128 (discarded, out of range)
AUS3: -2 °C (discarded, out of range)
And a lot of zeros. The rest doesn't have alternative registers.

So, at the end we find 5 useful temperatures.
Nothing looks out of the ordinary here, everything works as I would expect it from the docs of the NCT6796D.

But in the old version you seem to also get temperature source 16 (PECI0).
Don't get confused here, what was previously called CPU (PECI) is actually source 2 (CPU) and what previously was called CPU is actually the PECI and missing in the moment.
Looking at the old code it cannot have come from alternative registers, because this is null for PECI0.

All in the all I cannot really see the problem in the moment.
But by now I've also managed to confuse myself thoroughly.

Please do the following:
- Old version without any changes: Screenshot of all temperatures.
- New version as it is in the moment: Screenshot and the log of the first readout (log file until the second "Updating temperatures.".
- New version but with the board configuration copied over: Screenshot and log of first readout.
- Also a screenshot of HWINFO and MSI Dragon.
If possible everything close enough to each other that temperatures don't change too much.

**Comment by PhyxionNL** [comment]
Thanks for looking into it. The old version is the same as the screenshot above. HWiNFO and HWMonitor both have ~40 degrees for CPU/PECI. MSI Dragon software doesn't list that.

image

Here is the new log: https://pastebin.com/raw/1AdxfsRn

I initially thought that perhaps they use the same sensor for PCH and CPU/PECI but there sometimes is a difference of ~1 degree.

**Comment by Pomianowski** [comment]
> Thanks for looking into it. The old version is the same as the screenshot above. HWiNFO and HWMonitor both have ~40 degrees for CPU/PECI. MSI Dragon software doesn't list that.
> 
> image
> 
> Here is the new log: https://pastebin.com/raw/1AdxfsRn
> 
> I initially thought that perhaps they use the same sensor for PCH and CPU/PECI but there sometimes is a difference of ~1 degree.

Hey @PhyxionNL, Can you please tell me how can I create logs like this for my motherboard? ITE 8665E  
Where should I put Debug in the code

**Comment by holgerpieta** [comment]
> > Thanks for looking into it. The old version is the same as the screenshot above. HWiNFO and HWMonitor both have ~40 degrees for CPU/PECI. MSI Dragon software doesn't list that.
> > image
> > Here is the new log: https://pastebin.com/raw/1AdxfsRn
> > I initially thought that perhaps they use the same sensor for PCH and CPU/PECI but there sometimes is a difference of ~1 degree.
> 
> Hey @PhyxionNL, Can you please tell me how can I create logs like this for my motherboard? ITE 8665E
> Where should I put Debug in the code

Hey @Pomianowski,
unfortunately there is no general debug output coded in the SW, I just added some for NCT679X chips. Like me, @PhyxionNL has a board that uses one of those chips, so he can use my code to generate the debug output and we can look for errors.
If you happen to have a board that also uses one of those chips, you have to use the code from this PR and then enable the debug output according to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/339#issuecomment-736796654
You can use the PR's code by either building yourself or by using the artifacts generated by the CI test build. @PhyxionNL, do you know where to find them?

**Comment by holgerpieta** [comment]
> 
> 
> Thanks for looking into it. The old version is the same as the screenshot above. HWiNFO and HWMonitor both have ~40 degrees for CPU/PECI. MSI Dragon software doesn't list that.
> 
> image
> 
> Here is the new log: https://pastebin.com/raw/1AdxfsRn
> 
> I initially thought that perhaps they use the same sensor for PCH and CPU/PECI but there sometimes is a difference of ~1 degree.

Ok, I cannot see anything wrong anymore except the temperature names for your MSI board, so I pushed an update.
If you can, please run MSI Dragon, HWINFO and the new version in parallel for a while (ideally with and without load) to see if any of the sensors need to be renamed.
Other than that I would say the PR is ready to be merged. Did I miss anything?

**Comment by PhyxionNL** [comment]
Alright, I verified with BIOS and it's seems good to me. I don't know where HWiNFO is reading that sensor from, I do not see it in BIOS but there are only two temperature sensors there, which now match. Merged, thanks @holgerpieta!
