### PR TITLE
FIX Correctly Initialize NCT67XX registries

### LINKED ISSUE #2050: ASRock X570 Phantom Gaming 4 temperature sensors disappeared
Two temperature sensors have disappeared from the ASRock X570 Phantom Gaming 4. I discovered this when upgrading FanControl.

I went through the master branch build actions artifacts, and the last version with all 3 sensors was b1b76c3. The next build after that which ran was f5d5d3e, which is missing the chipset sensor. That continued until 7aff2a8, when the CPU sensor also disappeared.

Here is a screenshot of all three versions running side by side.

Image

### PR DESCRIPTION
**Pull request by Betalos**
Closes #2050

### CODE REVIEW

File: LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Nct677X.cs [hunk 1]
```diff
@@ -185,79 +185,139 @@ public Nct677X(LpcPort lpcPort, Chip chip, byte revision, ushort port)
...
-                    case Chip.NCT6792D:
+                    // --- GROUP A: NCT6793D/6795D (Common features, separated from 6796/98 by AUXTIN4/TSENSOR) ---
                     case Chip.NCT6793D:
                     case Chip.NCT6795D:
+                    case Chip.NCT6791D: // Assuming 6791/92 use a similar core map but less features than 6795
+                    case Chip.NCT6792D:
+                    case Chip.NCT6701D: // Defaulting to this group if map is less feature-rich than 6796/98
+                        temperaturesSources.AddRange(new TemperatureSourceData[]
+                        {
+                        // Note: Linux labels start at index 1 (0 is empty).
```
Comment (Blacktempel) [inline LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Nct677X.cs]: From here it seems to be missing an indentation level.

Comment (Betalos) [reply LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Nct677X.cs]: Done.
