### PR TITLE
Bugfix: Fan and Temp data missing #780

### LINKED ISSUE #614: [FanControl] Can't control fans on ASUS TUF B450M-PRO GAMING mobo
Hello. I have a ASUS TUF B450M-PRO GAMING motherboard and FanControl tool can't do anything with any of fans connected to it (while GPU fans are fine). Changing speeds do absolutely nothing. There are RPM values, but they are obviously incorrect with 1 fan showing something like 27 RPM and 2 others showing something around 3000 RPM, while in fact all of them are at 500-600 RPM.

Which should be an issue of LibreHardwareMonitor not supporting this motherboard. Is it possible to fix this?

For instance, HWiNFO64 shows RPM values of all the fans correctly.

### LINKED ISSUE #760: ASUS PRIME B450-PLUS: fan control doesnt work and fan sensors show incorrect RPM.
image
image
I see a lot issues about same problem on wide variety of Asus motherboards so here I am.
Just one more thing I discovered: usually i able to control one out of four my fan controllers, but this number randomly increases if "asus ai suite" (official asus utility for many thing and especially fan control) is working. This behavior is very inconsistent and controllable fans changing every time.

### PR DESCRIPTION
**Pull request by keif888**
This is a fix for #780 IT8655E which shows incorrect/missing information for fans and temps.  Also fixes #614.

I have tested this on my ASUS Prime B350M-A, through a number of restarts, sleeps and hibernates, and I no longer see the incorrect fan speeds, incorrect temperatures or missing temperatures.

Inspiration came from [Linux it87](https://github.com/frankcrawford/it87/blob/14b1de2fb49db4e73b58177bc43daa71ceb8e92f/it87.c#L3870) where the interaction with the IT8655E does a set_bank before every interaction with a port.

In theory this fix can be applied to other IT86 chipsets as per FEAT_BANK_SEL as shown [here](https://github.com/frankcrawford/it87/blob/14b1de2fb49db4e73b58177bc43daa71ceb8e92f/it87.c#L709) for the IT8655.
As I can't test other chipsets I have not made the changes.

Setting _requiresBankSelect to true for other chipsets that have this issue may fix them as well.  
eg. Issue #760 could be fixed as per below.

LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\IT87XX.cs
```
@@ -135,6 +135,7 @@ internal class IT87XX : ISuperIO
                Temperatures = new float?[6];
                Fans = new float?[6];
                Controls = new float?[5];
+                _requiresBankSelect = true;  // Fix #760
                break;

            case Chip.IT8688E:
```

### CODE REVIEW

**Comment by keif888** [comment]
The following issues may also be addressed with this pull.
#246, #277, #349, #433, #709, #735, #737, #855, #952, #970, #1148, #1336.

File: LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs [hunk 1]
```diff
@@ -33,6 +33,7 @@ internal class IT87XX : ISuperIO
     private readonly byte _version;
     private readonly float _voltageGain;
     private IGigabyteController _gigabyteController;
+    private readonly bool _requiresBankSelect;  // Fix #780 Set to true for those chips that need a SelectBank(0) to fix dodgy temps and fan speeds
```
Comment (PhyxionNL) [inline LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs:36]: I think just this comment is enough, so the ones below can be removed.

**Review by PhyxionNL — CHANGES_REQUESTED** [review]
Thanks for looking into this :)

**Comment by keif888** [comment]
1st time I'm using a pull request and review.  Hoping that I'm getting the workflow right.
